import type { Recipe, MapLocation } from './types';

export const recipes: Recipe[] = [
  {
    id: '1',
    title: 'Spicy Tomato Pasta',
    description: 'A quick and delicious pasta dish with a spicy tomato sauce, perfect for a weeknight dinner.',
    author: 'Jane Doe',
    authorImage: 'https://i.pravatar.cc/150?u=jane_doe',
    ingredients: [
      { item: 'Pasta', quantity: '500g' },
      { item: 'Canned Tomatoes', quantity: '1 can' },
      { item: 'Garlic', quantity: '2 cloves' },
      { item: 'Chili Flakes', quantity: '1 tsp' },
      { item: 'Olive Oil', quantity: '2 tbsp' },
      { item: 'Basil', quantity: 'a handful' },
    ],
    instructions: [
      'Cook pasta according to package directions.',
      'In a saucepan, heat olive oil over medium heat. Add minced garlic and chili flakes, cook until fragrant.',
      'Pour in canned tomatoes, breaking them up with a spoon. Simmer for 10 minutes.',
      'Drain pasta and add to the sauce. Stir to combine.',
      'Serve topped with fresh basil.',
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    tags: ['Quick', 'Vegan'],
    nutrition: {
      calories: 450,
      protein: 15,
      fat: 10,
      carbs: 75,
    },
    price: 12.99,
    location: 'San Francisco, CA',
    contact: 'jane.doe@example.com',
  },
  {
    id: '2',
    title: 'Gluten-Free Chocolate Cake',
    description: 'A rich and moist chocolate cake that you would never guess is gluten-free.',
    author: 'John Smith',
    authorImage: 'https://i.pravatar.cc/150?u=john_smith',
    ingredients: [
      { item: 'Gluten-Free Flour', quantity: '2 cups' },
      { item: 'Sugar', quantity: '1 cup' },
      { item: 'Cocoa Powder', quantity: '3/4 cup' },
      { item: 'Baking Soda', quantity: '1.5 tsp' },
      { item: 'Eggs', quantity: '2' },
      { item: 'Vegetable Oil', quantity: '1/2 cup' },
    ],
    instructions: [
      'Preheat oven to 350°F (175°C). Grease and flour two 9-inch round pans.',
      'In a large bowl, whisk together flour, sugar, cocoa, and baking soda.',
      'Add eggs and oil, and beat on medium speed for 2 minutes.',
      'Pour batter evenly into prepared pans.',
      'Bake for 30 to 35 minutes, or until a wooden skewer inserted into the center comes out clean.',
      'Let cool in pans for 10 minutes before moving to a wire rack to cool completely.',
    ],
    prepTime: 20,
    cookTime: 35,
    servings: 8,
    tags: ['Gluten-Free'],
    nutrition: {
      calories: 320,
      protein: 5,
      fat: 18,
      carbs: 38,
    },
    price: 24.50,
    location: 'Oakland, CA',
    contact: 'john.smith@example.com',
  },
  {
    id: '3',
    title: 'Avocado Toast with a Twist',
    description: 'The classic avocado toast, elevated with feta cheese and a sprinkle of red pepper flakes.',
    author: 'Alice Johnson',
    authorImage: 'https://i.pravatar.cc/150?u=alice_j',
    ingredients: [
      { item: 'Sourdough Bread', quantity: '2 slices' },
      { item: 'Avocado', quantity: '1' },
      { item: 'Feta Cheese', quantity: '2 tbsp' },
      { item: 'Red Pepper Flakes', quantity: 'a pinch' },
      { item: 'Lemon Juice', quantity: '1 tsp' },
    ],
    instructions: [
      'Toast the sourdough bread slices to your liking.',
      'In a small bowl, mash the avocado with lemon juice.',
      'Spread the mashed avocado on the toast.',
      'Top with crumbled feta cheese and a pinch of red pepper flakes.',
      'Serve immediately.',
    ],
    prepTime: 5,
    cookTime: 5,
    servings: 1,
    tags: ['Quick'],
    nutrition: {
      calories: 380,
      protein: 12,
      fat: 25,
      carbs: 30,
    },
    price: 9.75,
    location: 'Berkeley, CA',
    contact: 'alice.j@example.com',
  },
  {
    id: '4',
    title: 'Summer Berry Salad',
    description: 'A refreshing and light salad, packed with mixed greens, fresh berries, and a tangy vinaigrette.',
    author: 'Mike Brown',
    authorImage: 'https://i.pravatar.cc/150?u=mike_b',
    ingredients: [
        { item: 'Mixed Greens', quantity: '5 oz' },
        { item: 'Strawberries, sliced', quantity: '1 cup' },
        { item: 'Blueberries', quantity: '1/2 cup' },
        { item: 'Goat Cheese, crumbled', quantity: '1/4 cup' },
        { item: 'Walnuts, toasted', quantity: '1/4 cup' },
        { item: 'Balsamic Vinaigrette', quantity: '3 tbsp' },
    ],
    instructions: [
        'In a large bowl, combine the mixed greens, strawberries, and blueberries.',
        'Gently toss with balsamic vinaigrette.',
        'Sprinkle goat cheese and toasted walnuts over the top.',
        'Serve immediately as a light lunch or side dish.',
    ],
    prepTime: 15,
    cookTime: 0,
    servings: 2,
    tags: ['Quick', 'Gluten-Free'],
    nutrition: {
        calories: 280,
        protein: 8,
        fat: 20,
        carbs: 18,
    },
    price: 14.00,
    location: 'San Mateo, CA',
    contact: 'mike.b@example.com',
  },
  {
    id: '5',
    title: 'One-Pan Lemon Herb Chicken',
    description: 'A complete meal cooked on a single sheet pan, featuring tender chicken and roasted vegetables with a lemon-herb sauce.',
    author: 'Sarah Lee',
    authorImage: 'https://i.pravatar.cc/150?u=sarah_l',
    ingredients: [
        { item: 'Chicken Thighs', quantity: '4' },
        { item: 'Baby Potatoes, halved', quantity: '1 lb' },
        { item: 'Broccoli Florets', quantity: '1 head' },
        { item: 'Olive Oil', quantity: '3 tbsp' },
        { item: 'Lemon, juiced and zested', quantity: '1' },
        { item: 'Dried Oregano', quantity: '1 tsp' },
        { item: 'Dried Thyme', quantity: '1 tsp' },
    ],
    instructions: [
        'Preheat oven to 400°F (200°C).',
        'On a large sheet pan, toss potatoes and broccoli with 2 tbsp olive oil, salt, and pepper.',
        'In a small bowl, mix remaining 1 tbsp olive oil, lemon juice, lemon zest, oregano, and thyme.',
        'Pat chicken thighs dry and season with salt and pepper. Place on the sheet pan among the vegetables.',
        'Brush the lemon-herb mixture over the chicken and vegetables.',
        'Roast for 25-30 minutes, or until chicken is cooked through and vegetables are tender.',
    ],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    tags: ['Quick', 'Gluten-Free'],
    nutrition: {
        calories: 550,
        protein: 40,
        fat: 35,
        carbs: 20,
    },
    price: 18.25,
    location: 'Palo Alto, CA',
    contact: 'sarah.l@example.com',
  },
    {
    id: '6',
    title: 'Vegan Lentil Soup',
    description: 'A hearty and nutritious vegan lentil soup that is easy to make and full of flavor.',
    author: 'Chris Green',
    authorImage: 'https://i.pravatar.cc/150?u=chris_g',
    ingredients: [
        { item: 'Brown Lentils', quantity: '1 cup' },
        { item: 'Vegetable Broth', quantity: '4 cups' },
        { item: 'Diced Onion', quantity: '1' },
        { item: 'Carrots, chopped', quantity: '2' },
        { item: 'Celery, chopped', quantity: '2 stalks' },
        { item: 'Cumin', quantity: '1 tsp' },
    ],
    instructions: [
        'Rinse lentils.',
        'In a large pot, sauté onion, carrots, and celery until softened.',
        'Add lentils, vegetable broth, and cumin. Bring to a boil.',
        'Reduce heat and simmer for 25-30 minutes, until lentils are tender.',
        'Season with salt and pepper to taste.',
    ],
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    tags: ['Vegan', 'Gluten-Free', 'Quick'],
    nutrition: {
        calories: 250,
        protein: 15,
        fat: 2,
        carbs: 45,
    },
    price: 11.00,
    location: 'San Jose, CA',
    contact: 'chris.g@example.com',
  },
];

export const mapLocations: MapLocation[] = [
  {
    id: 'loc1',
    name: "Tony's Pasta Place",
    recipeId: '1',
    recipeTitle: 'Spicy Tomato Pasta',
    position: { lat: 34.0522, lng: -118.2437 },
  },
  {
    id: 'loc2',
    name: 'The Sweet Spot Bakery',
    recipeId: '2',
    recipeTitle: 'Gluten-Free Chocolate Cake',
    position: { lat: 34.055, lng: -118.25 },
  },
  {
    id: 'loc3',
    name: "Avocado & Co.",
    recipeId: '3',
    recipeTitle: 'Avocado Toast with a Twist',
    position: { lat: 34.048, lng: -118.24 },
  },
  {
    id: 'loc4',
    name: "The Chicken Roost",
    recipeId: '5',
    recipeTitle: 'One-Pan Lemon Herb Chicken',
    position: { lat: 34.06, lng: -118.23 },
  },
];

export const dummyOrders = [
    { id: 'ORD001', user: 'Bob Johnson', timestamp: '2024-05-20 10:30 AM' },
    { id: 'ORD002', user: 'Charlie Brown', timestamp: '2024-05-20 11:15 AM' },
    { id: 'ORD003', user: 'Diana Prince', timestamp: '2024-05-21 09:00 AM' },
];
