
export const users = [
  {
    name: 'Alice Johnson',
    email: 'alice@example.com',
    password: 'password123',
    image: 'https://i.pravatar.cc/150?u=alice@example.com',
    location: 'San Francisco, CA',
  },
  {
    name: 'Bob Williams',
    email: 'bob@example.com',
    password: 'password123',
    image: 'https://i.pravatar.cc/150?u=bob@example.com',
    location: 'Los Angeles, CA',
  },
    {
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    password: 'password123',
    image: 'https://i.pravatar.cc/150?u=charlie@example.com',
    location: 'San Diego, CA',
  },
  {
    name: 'Diana Prince',
    email: 'diana@example.com',
    password: 'password123',
    image: 'https://i.pravatar.cc/150?u=diana@example.com',
    location: 'San Francisco, CA',
  },
  {
    name: 'Ethan Hunt',
    email: 'ethan@example.com',
    password: 'password123',
    image: 'https://i.pravatar.cc/150?u=ethan@example.com',
    location: 'Los Angeles, CA',
  },
  {
    name: 'Fiona Glenanne',
    email: 'fiona@example.com',
    password: 'password123',
    image: 'https://i.pravatar.cc/150?u=fiona@example.com',
    location: 'San Diego, CA',
  },
  {
    name: 'George Costanza',
    email: 'george@example.com',
    password: 'password123',
    image: 'https://i.pravatar.cc/150?u=george@example.com',
    location: 'San Francisco, CA',
  },
  {
    name: 'Hannah Montana',
    email: 'hannah@example.com',
    password: 'password123',
    image: 'https://i.pravatar.cc/150?u=hannah@example.com',
    location: 'Los Angeles, CA',
  },
  {
    name: 'Indiana Jones',
    email: 'indy@example.com',
    password: 'password123',
    image: 'https://i.pravatar.cc/150?u=indy@example.com',
    location: 'San Diego, CA',
  },
  {
    name: 'Jack Sparrow',
    email: 'jack@example.com',
    password: 'password123',
    image: 'https://i.pravatar.cc/150?u=jack@example.com',
    location: 'San Francisco, CA',
  },
];

export const recipes = [
  {
    title: 'Spicy Tomato Pasta',
    description:
      'A quick and delicious pasta dish with a spicy tomato sauce, perfect for a weeknight dinner.',
    ingredients: [
      { quantity: '500g', item: 'Pasta' },
      { quantity: '1 can', item: 'Diced Tomatoes' },
      { quantity: '2 cloves', item: 'Garlic' },
      { quantity: '1 tsp', item: 'Red Pepper Flakes' },
      { quantity: '2 tbsp', item: 'Olive Oil' },
    ],
    instructions: [
      'Cook pasta according to package directions.',
      'While pasta cooks, heat olive oil in a large skillet over medium heat.',
      'Add minced garlic and red pepper flakes, and cook until fragrant, about 1 minute.',
      'Pour in diced tomatoes and bring to a simmer. Cook for 10 minutes, stirring occasionally.',
      'Drain pasta and add it to the skillet with the sauce. Toss to coat.',
      'Serve immediately with a sprinkle of parmesan cheese.',
    ],
    tags: ['Quick', 'Vegan'],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    authorName: 'Alice Johnson',
    price: 12.99,
  },
  {
    title: 'Gluten-Free Chocolate Cake',
    description:
      'A rich and moist chocolate cake that is completely gluten-free, made with almond flour.',
    ingredients: [
      { quantity: '1 cup', item: 'Almond Flour' },
      { quantity: '1/2 cup', item: 'Cocoa Powder' },
      { quantity: '1 tsp', item: 'Baking Soda' },
      { quantity: '1/2 cup', item: 'Maple Syrup' },
      { quantity: '2', item: 'Eggs' },
      { quantity: '1/4 cup', item: 'Coconut Oil' },
    ],
    instructions: [
      'Preheat oven to 350°F (175°C). Grease and flour an 8-inch round cake pan.',
      'In a large bowl, whisk together almond flour, cocoa powder, and baking soda.',
      'In a separate bowl, whisk together maple syrup, eggs, and melted coconut oil.',
      'Pour the wet ingredients into the dry ingredients and mix until just combined.',
      'Pour batter into the prepared pan and bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean.',
      'Let cool in the pan for 10 minutes before transferring to a wire rack to cool completely.',
    ],
    tags: ['Gluten-Free'],
    prepTime: 15,
    cookTime: 35,
    servings: 8,
    authorName: 'Bob Williams',
    price: 22.5,
  },
    {
    title: 'Avocado Toast with a Twist',
    description:
      'A simple but elegant avocado toast, elevated with feta cheese and a sprinkle of chili flakes.',
    ingredients: [
      { quantity: '2 slices', item: 'Sourdough Bread' },
      { quantity: '1', item: 'Avocado' },
      { quantity: '1/4 cup', item: 'Feta Cheese' },
      { quantity: '1/2 tsp', item: 'Chili Flakes' },
      { quantity: 'to taste', item: 'Salt and Pepper' },
    ],
    instructions: [
      'Toast the sourdough bread to your desired level of crispness.',
      'While the bread is toasting, mash the avocado in a small bowl. Season with salt and pepper.',
      'Spread the mashed avocado evenly over the toasted bread.',
      'Sprinkle with crumbled feta cheese and chili flakes.',
      'Serve immediately for the best taste and texture.',
    ],
    tags: ['Quick', 'Vegetarian'],
    prepTime: 5,
    cookTime: 5,
    servings: 1,
    authorName: 'Charlie Brown',
    price: 8.0,
  },
  {
    title: 'Summer Berry Salad',
    description:
      'A refreshing and light salad, perfect for a warm summer day, packed with fresh berries and a light vinaigrette.',
    ingredients: [
      { quantity: '5 oz', item: 'Mixed Greens' },
      { quantity: '1/2 cup', item: 'Strawberries, sliced' },
      { quantity: '1/2 cup', item: 'Blueberries' },
      { quantity: '1/4 cup', item: 'Goat Cheese, crumbled' },
      { quantity: '1/4 cup', item: 'Pecans, toasted' },
      { quantity: '3 tbsp', item: 'Balsamic Vinaigrette' },
    ],
    instructions: [
      'In a large salad bowl, combine the mixed greens, sliced strawberries, and blueberries.',
      'Sprinkle the crumbled goat cheese and toasted pecans over the top of the salad.',
      'Drizzle with balsamic vinaigrette just before serving.',
      'Toss gently to combine all ingredients.',
      'Serve as a light lunch or a side dish.',
    ],
    tags: ['Vegetarian', 'Gluten-Free'],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    authorName: 'Diana Prince',
    price: 15.0,
  },
  {
    title: 'One-Pan Lemon Herb Chicken',
    description:
      'An easy and flavorful one-pan meal, featuring tender chicken and roasted vegetables with a lemon herb sauce.',
    ingredients: [
      { quantity: '4', item: 'Chicken Thighs' },
      { quantity: '1 lb', item: 'Baby Potatoes, halved' },
      { quantity: '1', item: 'Lemon, thinly sliced' },
      { quantity: '2 tbsp', item: 'Olive Oil' },
      { quantity: '1 tsp', item: 'Dried Oregano' },
      { quantity: '1 tsp', item: 'Dried Thyme' },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'On a large baking sheet, toss the baby potatoes with olive oil, oregano, thyme, salt, and pepper.',
      'Arrange the chicken thighs on the baking sheet among the potatoes.',
      'Place lemon slices on top of the chicken and potatoes.',
      'Bake for 25-30 minutes, or until the chicken is cooked through and the potatoes are tender.',
      'Serve hot, with the pan juices spooned over the chicken and potatoes.',
    ],
    tags: ['Quick'],
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    authorName: 'Ethan Hunt',
    price: 18.75,
  },
  {
    title: 'Vegan Lentil Soup',
    description:
      'A hearty and nutritious vegan lentil soup, packed with vegetables and flavor.',
    ingredients: [
      { quantity: '1 cup', item: 'Brown or Green Lentils, rinsed' },
      { quantity: '1', item: 'Onion, chopped' },
      { quantity: '2', item: 'Carrots, chopped' },
      { quantity: '2', item: 'Celery Stalks, chopped' },
      { quantity: '4 cups', item: 'Vegetable Broth' },
      { quantity: '1 tsp', item: 'Cumin' },
    ],
    instructions: [
      'In a large pot or Dutch oven, heat a tablespoon of olive oil over medium heat.',
      'Add the chopped onion, carrots, and celery and cook until softened, about 5-7 minutes.',
      'Stir in the rinsed lentils, vegetable broth, and cumin.',
      'Bring the soup to a boil, then reduce heat and let it simmer for 25-30 minutes, or until the lentils are tender.',
      'Season with salt and pepper to taste.',
      'Serve hot, with a side of crusty bread for dipping.',
    ],
    tags: ['Vegan', 'Gluten-Free'],
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    authorName: 'Fiona Glenanne',
    price: 11.25,
  },
  {
    title: 'Classic Beef Tacos',
    description: 'A family-favorite recipe for classic beef tacos, easily customizable with your favorite toppings.',
    ingredients: [
        { quantity: '1 lb', item: 'Ground Beef' },
        { quantity: '1 packet', item: 'Taco Seasoning' },
        { quantity: '12', item: 'Taco Shells' },
        { quantity: '1 cup', item: 'Shredded Lettuce' },
        { quantity: '1 cup', item: 'Diced Tomatoes' },
        { quantity: '1 cup', item: 'Shredded Cheddar Cheese' },
    ],
    instructions: [
        'In a large skillet, cook the ground beef over medium-high heat until browned. Drain off any excess fat.',
        'Stir in the taco seasoning and water according to the packet instructions. Simmer for 5 minutes.',
        'While the meat is simmering, warm the taco shells in the oven according to package directions.',
        'Spoon the beef mixture into the taco shells.',
        'Top with lettuce, tomatoes, and cheese.',
        'Serve immediately with your favorite sides like sour cream and salsa.',
    ],

    tags: [],
    prepTime: 10,
    cookTime: 15,
    servings: 6,
    authorName: 'George Costanza',
    price: 14.50,
  },
  {
    title: 'Mushroom Risotto',
    description: 'A creamy and savory mushroom risotto that tastes like it came from a fancy restaurant.',
    ingredients: [
        { quantity: '1 tbsp', item: 'Olive Oil' },
        { quantity: '8 oz', item: 'Mushrooms, sliced' },
        { quantity: '1/2', item: 'Onion, chopped' },
        { quantity: '1 1/2 cups', item: 'Arborio Rice' },
        { quantity: '1/2 cup', item: 'Dry White Wine' },
        { quantity: '4 cups', item: 'Vegetable Broth, warmed' },
        { quantity: '1/2 cup', item: 'Grated Parmesan Cheese' },
    ],
    instructions: [
        'In a large skillet, heat olive oil over medium-high heat. Add mushrooms and cook until they have released their moisture and started to brown. Remove mushrooms and set aside.',
        'In the same skillet, add the chopped onion and cook until softened, about 3 minutes.',
        'Add the Arborio rice and toast for 1-2 minutes, stirring constantly.',
        'Pour in the white wine and cook until it has been completely absorbed by the rice.',
        'Add the warmed vegetable broth one ladleful at a time, stirring frequently. Wait until each addition is absorbed before adding the next.',
        'Continue until the rice is creamy and tender, about 20-25 minutes.',
        'Stir in the cooked mushrooms and Parmesan cheese. Season with salt and pepper to taste and serve immediately.',
    ],
    tags: ['Vegetarian', 'Gluten-Free'],
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    authorName: 'Hannah Montana',
    price: 19.99,
  },
  {
    title: 'Spicy Tuna Rolls',
    description: 'Learn how to make your own spicy tuna rolls at home with this easy-to-follow recipe.',
    ingredients: [
        { quantity: '1 cup', item: 'Sushi Rice, cooked' },
        { quantity: '2 sheets', item: 'Nori (Seaweed)' },
        { quantity: '6 oz', item: 'Sashimi-grade Tuna, finely chopped' },
        { quantity: '1 tbsp', item: 'Sriracha' },
        { quantity: '1 tbsp', item: 'Mayonnaise' },
        { quantity: '1', item: 'Cucumber, julienned' },
    ],
    instructions: [
        'In a small bowl, mix together the finely chopped tuna, Sriracha, and mayonnaise.',
        'Place a sheet of nori on a bamboo sushi mat, shiny side down.',
        'Wet your hands and spread a thin, even layer of sushi rice over the nori, leaving a 1-inch border at the top.',
        'Arrange a line of the spicy tuna mixture and julienned cucumber across the center of the rice.',
        'Tightly roll the sushi from the bottom up using the bamboo mat to help you form a tight cylinder.',
        'Moisten the top border of the nori with a little water to seal the roll.',
        'Use a very sharp, wet knife to slice the roll into 8 pieces. Serve with soy sauce, wasabi, and pickled ginger.',
    ],
    tags: [],
    prepTime: 20,
    cookTime: 20, // for the rice
    servings: 2,
    authorName: 'Indiana Jones',
    price: 25.00,
  },
  {
    title: 'Blueberry Pancakes',
    description: 'Fluffy, golden-brown pancakes studded with juicy blueberries. The perfect weekend breakfast.',
    ingredients: [
        { quantity: '1 1/2 cups', item: 'All-Purpose Flour' },
        { quantity: '2 tbsp', item: 'Sugar' },
        { quantity: '2 tsp', item: 'Baking Powder' },
        { quantity: '1/2 tsp', item: 'Salt' },
        { quantity: '1 1/4 cups', item: 'Milk' },
        { quantity: '1', item: 'Egg' },
        { quantity: '2 tbsp', item: 'Melted Butter' },
        { quantity: '1 cup', item: 'Fresh Blueberries' },
    ],
    instructions: [
        'In a large bowl, whisk together the flour, sugar, baking powder, and salt.',
        'In a separate medium bowl, whisk together the milk, egg, and melted butter.',
        'Pour the wet ingredients into the dry ingredients and stir until just combined. Do not overmix; a few lumps are okay.',
        'Gently fold in the blueberries.',
        'Heat a lightly oiled griddle or frying pan over medium-high heat. Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake.',
        'Cook until bubbles appear on the surface and the edges are dry, about 2-3 minutes. Flip and cook until golden brown on the other side.',
        'Serve hot with butter and maple syrup.',
    ],
    tags: ['Vegetarian'],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    authorName: 'Jack Sparrow',
    price: 9.50,
  },
];
